// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: dice-throws_protos/dice-throws.proto

package pachuco_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ThrowIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdRequest     string                 `protobuf:"bytes,1,opt,name=IdRequest,proto3" json:"IdRequest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThrowIdRequest) Reset() {
	*x = ThrowIdRequest{}
	mi := &file_dice_throws_protos_dice_throws_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThrowIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThrowIdRequest) ProtoMessage() {}

func (x *ThrowIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dice_throws_protos_dice_throws_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThrowIdRequest.ProtoReflect.Descriptor instead.
func (*ThrowIdRequest) Descriptor() ([]byte, []int) {
	return file_dice_throws_protos_dice_throws_proto_rawDescGZIP(), []int{0}
}

func (x *ThrowIdRequest) GetIdRequest() string {
	if x != nil {
		return x.IdRequest
	}
	return ""
}

type ThrowRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	HousePlayerId      string                 `protobuf:"bytes,1,opt,name=house_player_id,json=housePlayerId,proto3" json:"house_player_id,omitempty"`
	ContestantPlayerId string                 `protobuf:"bytes,2,opt,name=contestant_player_id,json=contestantPlayerId,proto3" json:"contestant_player_id,omitempty"`
	HouseDice          []int32                `protobuf:"varint,3,rep,packed,name=house_dice,json=houseDice,proto3" json:"house_dice,omitempty"`
	ContestantDice     []int32                `protobuf:"varint,4,rep,packed,name=contestant_dice,json=contestantDice,proto3" json:"contestant_dice,omitempty"`
	BetAmount          float32                `protobuf:"fixed32,5,opt,name=bet_amount,json=betAmount,proto3" json:"bet_amount,omitempty"`
	GameId             string                 `protobuf:"bytes,6,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	GameRound          int32                  `protobuf:"varint,7,opt,name=game_round,json=gameRound,proto3" json:"game_round,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ThrowRequest) Reset() {
	*x = ThrowRequest{}
	mi := &file_dice_throws_protos_dice_throws_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThrowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThrowRequest) ProtoMessage() {}

func (x *ThrowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dice_throws_protos_dice_throws_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThrowRequest.ProtoReflect.Descriptor instead.
func (*ThrowRequest) Descriptor() ([]byte, []int) {
	return file_dice_throws_protos_dice_throws_proto_rawDescGZIP(), []int{1}
}

func (x *ThrowRequest) GetHousePlayerId() string {
	if x != nil {
		return x.HousePlayerId
	}
	return ""
}

func (x *ThrowRequest) GetContestantPlayerId() string {
	if x != nil {
		return x.ContestantPlayerId
	}
	return ""
}

func (x *ThrowRequest) GetHouseDice() []int32 {
	if x != nil {
		return x.HouseDice
	}
	return nil
}

func (x *ThrowRequest) GetContestantDice() []int32 {
	if x != nil {
		return x.ContestantDice
	}
	return nil
}

func (x *ThrowRequest) GetBetAmount() float32 {
	if x != nil {
		return x.BetAmount
	}
	return 0
}

func (x *ThrowRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *ThrowRequest) GetGameRound() int32 {
	if x != nil {
		return x.GameRound
	}
	return 0
}

type ThrowResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	HousePlayerId      string                 `protobuf:"bytes,3,opt,name=house_player_id,json=housePlayerId,proto3" json:"house_player_id,omitempty"`
	ContestantPlayerId string                 `protobuf:"bytes,4,opt,name=contestant_player_id,json=contestantPlayerId,proto3" json:"contestant_player_id,omitempty"`
	HouseDice          []int32                `protobuf:"varint,5,rep,packed,name=house_dice,json=houseDice,proto3" json:"house_dice,omitempty"`
	ContestantDice     []int32                `protobuf:"varint,6,rep,packed,name=contestant_dice,json=contestantDice,proto3" json:"contestant_dice,omitempty"`
	BetAmount          float32                `protobuf:"fixed32,7,opt,name=bet_amount,json=betAmount,proto3" json:"bet_amount,omitempty"`
	GameId             string                 `protobuf:"bytes,8,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	GameRound          int32                  `protobuf:"varint,9,opt,name=game_round,json=gameRound,proto3" json:"game_round,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ThrowResponse) Reset() {
	*x = ThrowResponse{}
	mi := &file_dice_throws_protos_dice_throws_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThrowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThrowResponse) ProtoMessage() {}

func (x *ThrowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dice_throws_protos_dice_throws_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThrowResponse.ProtoReflect.Descriptor instead.
func (*ThrowResponse) Descriptor() ([]byte, []int) {
	return file_dice_throws_protos_dice_throws_proto_rawDescGZIP(), []int{2}
}

func (x *ThrowResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ThrowResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ThrowResponse) GetHousePlayerId() string {
	if x != nil {
		return x.HousePlayerId
	}
	return ""
}

func (x *ThrowResponse) GetContestantPlayerId() string {
	if x != nil {
		return x.ContestantPlayerId
	}
	return ""
}

func (x *ThrowResponse) GetHouseDice() []int32 {
	if x != nil {
		return x.HouseDice
	}
	return nil
}

func (x *ThrowResponse) GetContestantDice() []int32 {
	if x != nil {
		return x.ContestantDice
	}
	return nil
}

func (x *ThrowResponse) GetBetAmount() float32 {
	if x != nil {
		return x.BetAmount
	}
	return 0
}

func (x *ThrowResponse) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *ThrowResponse) GetGameRound() int32 {
	if x != nil {
		return x.GameRound
	}
	return 0
}

var File_dice_throws_protos_dice_throws_proto protoreflect.FileDescriptor

const file_dice_throws_protos_dice_throws_proto_rawDesc = "" +
	"\n" +
	"$dice-throws_protos/dice-throws.proto\x12\rpachuco_proto\x1a\x1agoogle/api/timestamp.proto\".\n" +
	"\x0eThrowIdRequest\x12\x1c\n" +
	"\tIdRequest\x18\x01 \x01(\tR\tIdRequest\"\x87\x02\n" +
	"\fThrowRequest\x12&\n" +
	"\x0fhouse_player_id\x18\x01 \x01(\tR\rhousePlayerId\x120\n" +
	"\x14contestant_player_id\x18\x02 \x01(\tR\x12contestantPlayerId\x12\x1d\n" +
	"\n" +
	"house_dice\x18\x03 \x03(\x05R\thouseDice\x12'\n" +
	"\x0fcontestant_dice\x18\x04 \x03(\x05R\x0econtestantDice\x12\x1d\n" +
	"\n" +
	"bet_amount\x18\x05 \x01(\x02R\tbetAmount\x12\x17\n" +
	"\agame_id\x18\x06 \x01(\tR\x06gameId\x12\x1d\n" +
	"\n" +
	"game_round\x18\a \x01(\x05R\tgameRound\"\xd3\x02\n" +
	"\rThrowResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12&\n" +
	"\x0fhouse_player_id\x18\x03 \x01(\tR\rhousePlayerId\x120\n" +
	"\x14contestant_player_id\x18\x04 \x01(\tR\x12contestantPlayerId\x12\x1d\n" +
	"\n" +
	"house_dice\x18\x05 \x03(\x05R\thouseDice\x12'\n" +
	"\x0fcontestant_dice\x18\x06 \x03(\x05R\x0econtestantDice\x12\x1d\n" +
	"\n" +
	"bet_amount\x18\a \x01(\x02R\tbetAmount\x12\x17\n" +
	"\agame_id\x18\b \x01(\tR\x06gameId\x12\x1d\n" +
	"\n" +
	"game_round\x18\t \x01(\x05R\tgameRound2\xb8\x02\n" +
	"\tDiceThrow\x12F\n" +
	"\tSaveThrow\x12\x1b.pachuco_proto.ThrowRequest\x1a\x1c.pachuco_proto.ThrowResponse\x12G\n" +
	"\bGetThrow\x12\x1d.pachuco_proto.ThrowIdRequest\x1a\x1c.pachuco_proto.ThrowResponse\x12L\n" +
	"\rGetUserThrows\x12\x1d.pachuco_proto.ThrowIdRequest\x1a\x1c.pachuco_proto.ThrowResponse\x12L\n" +
	"\rGetGameThrows\x12\x1d.pachuco_proto.ThrowIdRequest\x1a\x1c.pachuco_proto.ThrowResponseB\"Z github.com/monguis/pachuco-protob\x06proto3"

var (
	file_dice_throws_protos_dice_throws_proto_rawDescOnce sync.Once
	file_dice_throws_protos_dice_throws_proto_rawDescData []byte
)

func file_dice_throws_protos_dice_throws_proto_rawDescGZIP() []byte {
	file_dice_throws_protos_dice_throws_proto_rawDescOnce.Do(func() {
		file_dice_throws_protos_dice_throws_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dice_throws_protos_dice_throws_proto_rawDesc), len(file_dice_throws_protos_dice_throws_proto_rawDesc)))
	})
	return file_dice_throws_protos_dice_throws_proto_rawDescData
}

var file_dice_throws_protos_dice_throws_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dice_throws_protos_dice_throws_proto_goTypes = []any{
	(*ThrowIdRequest)(nil),        // 0: pachuco_proto.ThrowIdRequest
	(*ThrowRequest)(nil),          // 1: pachuco_proto.ThrowRequest
	(*ThrowResponse)(nil),         // 2: pachuco_proto.ThrowResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_dice_throws_protos_dice_throws_proto_depIdxs = []int32{
	3, // 0: pachuco_proto.ThrowResponse.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: pachuco_proto.DiceThrow.SaveThrow:input_type -> pachuco_proto.ThrowRequest
	0, // 2: pachuco_proto.DiceThrow.GetThrow:input_type -> pachuco_proto.ThrowIdRequest
	0, // 3: pachuco_proto.DiceThrow.GetUserThrows:input_type -> pachuco_proto.ThrowIdRequest
	0, // 4: pachuco_proto.DiceThrow.GetGameThrows:input_type -> pachuco_proto.ThrowIdRequest
	2, // 5: pachuco_proto.DiceThrow.SaveThrow:output_type -> pachuco_proto.ThrowResponse
	2, // 6: pachuco_proto.DiceThrow.GetThrow:output_type -> pachuco_proto.ThrowResponse
	2, // 7: pachuco_proto.DiceThrow.GetUserThrows:output_type -> pachuco_proto.ThrowResponse
	2, // 8: pachuco_proto.DiceThrow.GetGameThrows:output_type -> pachuco_proto.ThrowResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dice_throws_protos_dice_throws_proto_init() }
func file_dice_throws_protos_dice_throws_proto_init() {
	if File_dice_throws_protos_dice_throws_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dice_throws_protos_dice_throws_proto_rawDesc), len(file_dice_throws_protos_dice_throws_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dice_throws_protos_dice_throws_proto_goTypes,
		DependencyIndexes: file_dice_throws_protos_dice_throws_proto_depIdxs,
		MessageInfos:      file_dice_throws_protos_dice_throws_proto_msgTypes,
	}.Build()
	File_dice_throws_protos_dice_throws_proto = out.File
	file_dice_throws_protos_dice_throws_proto_goTypes = nil
	file_dice_throws_protos_dice_throws_proto_depIdxs = nil
}
